title: LaTeX CV with Biblatex
description: CV built entirely with LaTeX. Made for academics with Biblatex integration. MIT licensed.
google_analytics: UA-85626326-1

plugins:
  - jekyll-titles-from-headings
  - jekyll-remote-theme

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

show_downloads: true

remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman