title: LaTeX CV with Biblatex
description: CV built entirely with LaTeX. Made for academics with Biblatex integration. Deployed with GitHub Pages. MIT licensed.

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

show_downloads: true

theme: jekyll-theme-cayman